style: fixed build
/usr/bin/ld: PrlCleanup.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line

Signed-off-by: Igor Sukhih <igor@virtuozzo.com>